particle:
    server:
        port: 8080
curated:
    apiVersion: v1
    apiKey: '${CURATED_API_KEY}'
    publicationKey: '${CURATED_PUBLICATION_KEY}'
router:
    static:
        resources:
            enabled: true
            mapping: /assets/**
            paths:
                - classpath:static
                - file:/Users/sdelamo/Downloads